### PR TITLE
ISSUE-67 - Enable doc_markdown clippy

### PR DESCRIPTION
**Pull request by jmcconnell26**
* Enable doc_markdown clippy
* Make changes to existing docs

Signed-off-by: joshmc <josh-mcc@tiscali.co.uk>

### CODE REVIEW

**Review by jiangliu — APPROVED** [review]

**Comment by alexandruag** [comment]
Hi, thanks for the PR! Some of the changed lines now exceed 100 chars in length. Can you please fix that as well?

**Comment by jmcconnell26** [comment]
Hi @alexandruag,

Of course, have pushed those changes now. Please let me know if anything else doesn't look OK.

Thanks,
Josh

**Comment by andreeaflorescu** [comment]
@jmcconnell26 can you also update the commit message and add the following line to it:

```Fixes: https://github.com/rust-vmm/vm-memory/issues/67```

This helps with:
- autoresolving the issue when the PR is merged
- tracing back the PRs that introduced changes

Otherwise, the PR looks good to me. I am wondering if this can also be enforced somehow at the rust-vmm-ci level so that all rust-vmm components benefit from this change.

**Comment by lauralt** [comment]
@jmcconnell26 Hi, the commit format test is failing, can you please also sign your commit: `git commit -s --amend`? Sorry about that :(.

**Review by jiangliu — APPROVED** [review]

**Comment by jmcconnell26** [comment]
@andreeaflorescu, have pushed that change to the commit message. I'd be interested in taking a look at enabling this at the rust-vmm-ci level if that's OK?
@lauralt apologies, have updated now.
Thanks,
Josh

**Comment by andreeaflorescu** [comment]
> @andreeaflorescu, have pushed that change to the commit message. I'd be interested in taking a look at enabling this at the rust-vmm-ci level if that's OK?

Yap, that would be super nice. We can open a corresponding issue in github.com/rust-vmm/rust-vmm-ci/ and discuss there how this can be achieved (I haven't looked at other ways of enabling this btw, so I am not sure it makes sense :))) )

**Review by andreeaflorescu — APPROVED** [review]

**Pull request merged**
