### PR TITLE
Normalize license statements

### LINKED ISSUE #13: Update License to Apache-v2.0 + 3-clause BSD
For details check https://github.com/rust-vmm/community/issues/14

### PR DESCRIPTION
**Pull request by jiangliu**
Normalize license statements as:
. BSD-3-Clause: code dirived from crosvm without modifications
. Apache2 or BSD-3-Clause: code dirived from crosvm with modifications
  and enhancements.
. Apache2: newly developed code

Signed-off-by: Liu Jiang <gerry@linux.alibaba.com>

Fix #13

### CODE REVIEW

**Comment by bonzini** [comment]
Apache2 for newly developed code is incompatible with GPLv2, so the decision was to go with Apache 2 or BSD-3-clause for everything. Since 3-clause BSD is a permissive license, it is possible to do so even for code derived from crosvm without modifications.

**Comment by jiangliu** [comment]
> Apache2 for newly developed code is incompatible with GPLv2, so the decision was to go with Apache 2 or BSD-3-clause for everything. Since 3-clause BSD is a permissive license, it is possible to do so even for code derived from crosvm without modifications.

So the plan is to license all files as "Apache2 OR BSD-3-Clause".
@tkreuzer May I change the license of file mmap_windows.rs to "Apache2 OR BSD-3-Clause"?

**Comment by bonzini** [comment]
@aghecenco Please read the discussion before approving; there was a request for changes before.

**Comment by aghecenco** [comment]
@bonzini sorry about that, I'd only looked at the changes. While I can't un-approve, I agree with your observation.

**Comment by jiangliu** [comment]
I have updated the license to "Apache2 OR BSD-3-Clause".
It's sensitive to change license, so we need explicitly approval from AWS, Google, Redhat and Timo Kreuzer <timo@crowdstrike.com>:)

**Comment by bonzini** [comment]
* Red Hat is okay

* Google gave okay at OpenStack PTG (and technically need not give approval because it's allowed by their own license)

* Amazon gave okay for Apache2 or MIT (so technically need not give further approval as well) and informally agreed with the plan at PTG

* @tkreuzer approval is needed

**Comment by bonzini** [comment]
@tkreuzer can you agree to re-release your changes under dual license Apache2 + MIT (instead of Apache2 + BSD)?

**Comment by tkreuzer** [comment]
Yes, I approve.

**Comment by andreeaflorescu** [comment]
@jiangliu can you please rebase the PR so we can merge it?

**Pull request merged**
