### PR TITLE
Typos in DESIGN.md

### PR DESCRIPTION
**Pull request by rvolgers**

### CODE REVIEW

**Comment by andreeaflorescu** [comment]
@rvolgers please sign your commit and than push -f:
```
git commit -s --amend --no-edit
git push -f
```

**Comment by rvolgers** [comment]
I created this pull request via the GitHub web interface. Making it a signed commit isn't a lot of work but I'm not sure I'll be able to find the time this weekend.

Sorry for the delay, should get to it next week probably.

**Comment by andreeaflorescu** [comment]
@rvolgers any update here?

**Comment by jiangliu** [comment]
This PR has been out-dated by latest commits, so close it.

**Pull request closed without merging**
