### PR TITLE
[ByteValued] improve unit tests

### PR DESCRIPTION
**Pull request by serban300**
- Rename ByteValued macros for consistency
- improve ByteValued associated unit tests

### CODE REVIEW

**Comment by bonzini** [comment]
I think PlainData is less clear than ByteValued (though that may not be a great name either); a ByteValued object can be sliced into bytes, while it's not clear what it means to be "plain" data. For example in C++ a "plain old data" type has no destructor, no assignment operator, etc. but it can have members of pointer type.

**Comment by serban300** [comment]
> I think PlainData is less clear than ByteValued (though that may not be a great name either); a ByteValued object can be sliced into bytes, while it's not clear what it means to be "plain" data. For example in C++ a "plain old data" type has no destructor, no assignment operator, etc. but it can have members of pointer type.

Ok, Makes sense. I reverted the renamings.

**Comment by bonzini** [comment]
@serban300 can you look into the CI failure so that we can merge the new tests? It seems like the buildkite configuration was broken.

**Comment by andreeaflorescu** [comment]
@bonzini the Windows CI machine was not available. That's why the tests were failing. I re-triggered the Windows CI and now they're all passing.

**Pull request merged**
