### PR TITLE
[GuestMemory] Add code examples

### PR DESCRIPTION
**Pull request by serban300**

### CODE REVIEW

**Comment by bonzini** [comment]
@andreeaflorescu Do you know what's happening with buildkite/vm-memory-ci?

**Comment by bonzini** [comment]
Hmm actually I missed that the test_map_fold() line is not commented. Not a huge deal but if you can push a fix for that and change the subject to "run the map_and_fold example as a test" it would be even better. With some luck that would wake up the CI too...

**Comment by andreeaflorescu** [comment]
@bonzini It's kinda random. I'll take a look.

**Comment by serban300** [comment]
> Hmm actually I missed that the test_map_fold() line is not commented. Not a huge deal but if you can push a fix for that and change the subject to "run the map_and_fold example as a test" it would be even better. With some luck that would wake up the CI too...

Sure. Done.

**Pull request merged**
